export { FilePreview, type FilePreviewProps } from './FilePreview'
export { FilePreviewNavigationProvider } from './FilePreviewNavigationProvider'
export { canProduceSelectionReference } from './filePreviewRegistry'
export { useOpenFilePreviewTab, useOptionalOpenFilePreviewTab } from './hooks/useOpenFilePreviewTab'
export type { FilePreviewType } from './types'
